### ISSUE TITLE
Can't save photo in HTC 

### ISSUE THREAD

**Issue by lab-explorer** [oliveiradev/RxPhoto#14]
I tried to request bitmap from camera but i got the error on htc one (m8).
Error text:
`E/HTCCamera: saveAndFinish() - Cannot save data to 'content://media/external/images/media/104203'
    java.io.FileNotFoundException: No entry for content://media/external/images/media/104203
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:973)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:715)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:691)
        at com.htc.camera.HTCCamera.saveAndFinish(HTCCamera.java:3649)
        at com.htc.camera.HTCCamera.returnRequestedMedia(HTCCamera.java:3585)
        at com.htc.camera.actionscreen.RequestActionScreen.onDoneClicked(RequestActionScreen.java:101)
        at com.htc.camera.actionscreen.RequestActionScreen.access$100(RequestActionScreen.java:26)
        at com.htc.camera.actionscreen.RequestActionScreen$2.onClick(RequestActionScreen.java:230)
        at android.view.View.performClick(View.java:5226)
        at android.view.View$PerformClick.run(View.java:21266)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:168)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
`

**Comment by GeniusRUS** [comment]
@enister hi!
Can you repeat the action with a third-party camera, for example, from Google?

**Comment by lab-explorer** [comment]
@GeniusRUS hi! Yeah, i repeated this action with camera api and through intent. It works!
